FROM python:3.7.6-slim-buster

COPY requirements.txt /opt/app/requirements.txt
WORKDIR /opt/app
RUN pip3 install python-telegram-bot pyTelegramBotAPI
RUN pip3 install -r requirements.txt

RUN pip3 install torch==1.3.1+cpu torchvision==0.4.2+cpu -f https://download.pytorch.org/whl/torch_stable.html

ADD resnet18-fulldata-model.pth /opt/app
ADD bot.py /opt/app

CMD [ "python", "./bot.py" ]